server:
  port: 2222

spring:
  application:
    name: compute-service

eureka:
  instance:
    hostname: localhost
  client:
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:1111/eureka/